[template.environment]
  GQL_HOST = "https://calero.nestor.codes/graphql"
  NUXT_IMAGE_DOMAINS = "calero.nestor.codes"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://calero.nestor.codes/.*"]
